# Generated by Django 6.0.1 on 2026-01-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_rename_country_id_city_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
