# Generated by Django 6.0.1 on 2026-01-31 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0008_review_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_rating', to='countries.city'),
        ),
    ]
